// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:054a0c48-7e6d-46d5-b939-e0168f7a5be5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_sYykGsnzh",
    "aws_user_pools_web_client_id": "6l6c6dm66gp7o12hcbest307el"
};


export default awsmobile;
